name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run development build
      run: npm run dev

    - name: Run production build
      run: npm run build

    - name: Check if app.zip exists
      run: |
        if [ ! -f build/app.zip ]; then
          echo "Error: app.zip not found!"
          exit 1
        fi

